import { useState, Suspense } from "react";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Stats } from "@react-three/drei";
import Cube from '../components/cube';
import styles from "../styles/Home.module.css";

export default function Home() {
  const [showPointer, setShowPointer] = useState(false);

  return (
    <div
      className={[
        styles["container"],
        showPointer && styles["force-hover"],
      ].join(" ")}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas style={{ height: "100vh", width: "100vw" }}>
        <Suspense fallback={null}>
          <axesHelper />
          <ambientLight />
          <Stats />
          <OrbitControls
            rotateSpeed={0.5}
            enableDamping
            dampingFactor={0.1}
            enablePan={false}
          />

          <Cube setShowPointer={setShowPointer} />
        </Suspense>
      </Canvas>
    </div>
  );
}

