import { useEffect, useState, Suspense } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import * as THREE from "three";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Stats } from "@react-three/drei";
import { Leva } from "leva";
import Cube from "../components/Cube";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [showPointer, setShowPointer] = useState(false);
  const [controlsEnabled, setControlsEnabled] = useState(false);
  const { query } = useRouter();

  useEffect(() => {
    const key = 'showcontrols'

    const hascontrolsEnabled = Object.keys(query).some((i) => i === key)
    if (!hascontrolsEnabled) {
      setControlsEnabled(false)
      return
    }

    const shouldHide = query[key] === 'false'
    if (shouldHide) {
      setControlsEnabled(false)
      return
    }

    setControlsEnabled(true)
  }, [query])

  return (
    <div
      className={[
        styles["container"],
        showPointer && styles["force-hover"],
      ].join(" ")}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Leva collapsed hidden={!controlsEnabled} />

      <Canvas
        style={{ height: "100vh", width: "100vw" }}
        onCreated={({ gl }) => (gl.toneMapping = THREE.NoToneMapping)}
      >
        <Suspense fallback={null}>
          {controlsEnabled && (
            <>
              <axesHelper />
              <Stats />
            </>
          )}

          <ambientLight />
          <OrbitControls
            enablePan={false}
            enableDamping
            dampingFactor={0.1}
            rotateSpeed={0.5}
            maxDistance={9}
          />

          <Cube setShowPointer={setShowPointer} />
        </Suspense>
      </Canvas>
    </div>
  );
}

